# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 872b94cdcbf07601cebbb9321a29312ca6bbeba3d1ef263b22e20efaeae74d11b48a283b018a792f7895cff9e169a6ad077dc7ba7f5f5cdbbe3ec6724c886460

test:
  secret_key_base: b0a5ebd176daff07d24407679312c08678a657d016e1c3604716639b147f2fc6f10eae4753014ec4a46d9a5a41f41146ef078e6cc33b02218eeb54c8004c9b69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
